image: node:9.11.1

pages:
  script:
  - npm install
  - npm run metadata:generate
  - npm run build
  - mv ./bundle ./public
  - cp --recursive ./website/* ./public/

  artifacts:
    paths:
    - public

  only:
  - master
