language: node_js
node_js:
  - "4.0"
  - "stable"
sudo: false
before_install:
  # Setup Node.js version-specific dependencies
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev istanbul"
# before_script:
#   - npm update -g npm
script:
  # Run test script, depending on istanbul install
  - "test -n $(npm -ps ls istanbul) || npm test"
  - "test -z $(npm -ps ls istanbul) || npm run-script test-travis"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
